package com.darktower.myfavoriteseries;

public class MyСonstants {

    public static final String t_The_Stand = "\tThe Stand is a post-apocalyptic dark fantasy novel written by American author Stephen King and first published in 1978 by Doubleday. The plot centers on a pandemic of a weaponized strain of influenza that kills almost the entire world population. The few survivors, united in groups, establish a new social system and engage in confrontation with each other. In writing the book, King sought to create an epic in the spirit of The Lord of the Rings that was set in contemporary America. The book was difficult for King to write because of the large number of characters and storylines.\n" +
            "\tIn 1990, The Stand was reprinted as a Complete and Uncut Edition. King restored some fragments of texts that were initially reduced, revised the order of the chapters, shifted the novel's setting from 1980 to 10 years forward, and accordingly corrected a number of cultural references. The Complete and Uncut Edition of The Stand is considered to be King's longest stand-alone work with its 1,152 pages, surpassing King's 1,138-page novel It. The book has sold 4.5 million copies.\n" +
            "\tThe Stand was highly appreciated by reviewers and is considered one of King's best novels. It has been included in lists of the best books of all time by Rolling Stone, Time, the Modern Library, Amazon and the BBC. Reviewers praised the believability of the story, the relevance of the issues raised and the liveliness of the characters, but criticized the protractedness of individual episodes, the plot dualism, and the deliberate denouement. A self-titled miniseries based on the novel was broadcast on ABC in 1994. From 2008 to 2012, Marvel Comics published a series of comics written by Roberto Aguirre-Sacasa and illustrated by Mike Perkins. A miniseries currently airing on CBS All Access completed production in March 2020.";

    public static final String t_The_Man_in_the_High_Castle = "\tThe Man in the High Castle is an American dystopian alternate history streaming television series depicting a parallel universe where the Axis powers of Nazi Germany and the Empire of Japan rule the world after their victory in World War II. It was created by Frank Spotnitz and is produced by Amazon Studios, Scott Free Productions, Headline Pictures, Electric Shepherd Productions, and Big Light Productions. The series is based on Philip K. Dick's 1962 novel of the same name.\n" +
            "\tIn the parallel universe, Germany and Japan have divided the United States into the Greater Nazi Reich in the east, with New York City as its regional capital, and the Japanese Pacific States to the west, with San Francisco as the capital. These territories are separated by a neutral zone that encompasses the Rocky Mountains. The series starts in 1962 and follows characters whose destinies intertwine when they come into contact with newsreels and home movies that show Germany and Japan losing the war. The title of the series refers to the mysterious figure believed to have created the footage.\n" +
            "\tThe pilot premiered in January 2015, and Amazon ordered a ten-episode season the following month which was released in November. A second season of ten episodes premiered in December 2016, and a third season was released on October 5, 2018. The fourth and final season premiered on November 15, 2019.";

    public static final String t_Gotham = "\tGotham is an American action crime drama television series developed by Bruno Heller, produced by Warner Bros. Television and based on characters published by DC Comics and appearing in the Batman franchise, primarily those of James Gordon and Bruce Wayne. The series premiered on Fox on September 20, 2013, and concluded on April 25, 2019. The series stars Ben McKenzie as Jim Gordon and David Mazouz as Bruce Wayne. The series was originally intended to focus only on Gordon's early days with the Gotham City Police Department, but they subsequently included the Bruce Wayne character and the origin stories of Batman's rogues gallery.\n" +
            "\tDevelopment for a prequel series based on Batman began in September 2012, with Bruno Heller hired by Fox to serve as a writer and executive producer. In March 2014, Fox originally ordered 16 episodes for its first season before expanding it to 22. Filming primarily took place across New York City. In May 2018, Fox renewed the series for a fifth and final season, consisting of 12 episodes, which premiered on January 3, 2019, and concluded on April 25, 2019.";

    public static final String t_The_Young_Pope = "\tThe Young Pope is a drama television series created and directed by Paolo Sorrentino for Sky Atlantic, HBO, and Canal+. The series stars Jude Law as the disruptive Pope Pius XIII and Diane Keaton as his confidante, Sister Mary, in a Vatican full of intrigues. The series was co-produced by the European production companies Wildside, Haut et Court TV, and Mediapro.\n" +
            "\tThe world premiere of The Young Pope was on 3 September 2016 at the 73rd Venice International Film Festival, where the first two episodes were screened out of competition, the first time in the history of the festival that a TV series has been a part of the program. The series premiered on television on 21 October 2016 on Sky Atlantic in Italy.\n" +
            "\tOriginally designed as a limited series, The Young Pope was marketed as such especially in the United States. However, Wildside producer Lorenzo Mieli announced on 20 October 2016 that a second season of the series was in development. Later, the project was revealed to be a follow-up miniseries called The New Pope, with Law returning and joined by John Malkovich. Production began in Italy in late 2018.\n" +
            "\tOn 14 July 2017, The Young Pope received two nominations for the 69th Primetime Creative Arts Emmy Awards, becoming the first Italian TV series to be nominated for a Primetime Emmy Award.";

    public static final String t_The_New_Pope = "\tThe New Pope is a drama television series created and directed by Paolo Sorrentino for Sky Atlantic, HBO and Canal+. It is a continuation of the 2016 series The Young Pope, originally announced as its second season. The nine-episode series stars Jude Law, reprising his role as Pope Pius XIII, and John Malkovich as Pope John Paul III, the titular new pope. It was co-produced by European production companies The Apartment, Wildside, Haut et Court TV and Mediapro.\n" +
            "\tThe series premiered on 10 January 2020 on Sky Atlantic in Italy.";

    public static final String t_Peaky_Blinders = "\tPeaky Blinders is a British period crime drama television series created by Steven Knight. Set in Birmingham, England, the series follows the exploits of the Shelby crime family in the direct aftermath of the First World War. The fictional family is loosely based on a real urban youth gang of the same name, who were active in the city from the 1890s to the early 20th century.\n" +
            "\tPeaky Blinders features an ensemble cast, led by Cillian Murphy, Helen McCrory, Joe Cole and Paul Anderson starring as Tommy Shelby, Elizabeth \"Polly\" Gray, John Shelby and Arthur Shelby respectively, the gang's senior members. Sam Neill, Tom Hardy, Paddy Considine, Adrien Brody, Aidan Gillen, Charlotte Riley, Sam Claflin and Anya Taylor-Joy also have recurring roles at various junctures of the series. The show premiered on 12 September 2013, telecast on BBC Two until the fourth series, and then shifted to BBC One for the fifth series.\n" +
            "\tIn 2018, after the show's Drama Series win at the BAFTA TV Awards, Knight confirmed his \"ambition of making it a story of a family between two wars, and by ending it with the first air raid siren in Birmingham\", which was 25 June 1940. The fifth series premiered on BBC One on 25 August 2019 and finished on 22 September 2019. Netflix, under the deal with Weinstein Company and Endemol, had acquired the rights to release Peaky Blinders in the United States and around the world. In January 2021, it was announced that the sixth series would be the final television series of Peaky Blinders.";

    public static final String t_El_Internado = "\tEl Internado (The Boarding School), also known as El Internado Laguna Negra (The Black Lagoon Boarding School) is a Spanish teen drama thriller television series focusing on the students of a fictional boarding school in a forest far from the city, on the outskirts of which macabre events occur. The series debuted on 24 May 2007, and is a production of Antena 3. The series began airing on Netflix on 15 July 2015, and stopped airing on 20 December 2017. The series was then reaired on 16 October 2018.\n" +
            "\tA reboot series, El Internado: Las Cumbres, will be released on Prime Video in February 2021.";

    public static final String t_Castle_Rock = "\tCastle Rock is an American psychological horror anthology streaming television series, featuring and inspired by characters, settings, and themes from the stories created by Stephen King and his fictional town of Castle Rock, Maine. The series premiered on July 25, 2018, on Hulu. It was created by Sam Shaw and Dustin Thomason, and stars André Holland, Melanie Lynskey, Bill Skarsgård, Jane Levy, and Sissy Spacek in its first season. On August 14, 2018, it was announced that the series had been renewed for a second season starring Lizzy Caplan, Paul Sparks, Barkhad Abdi, Yusra Warsama, Elsie Fisher, Matthew Alan and Tim Robbins, which premiered on October 23, 2019.\n" +
            "\tIn November 2020, Hulu canceled the series after two seasons.";





}
